Update Build

diff --git a/depends/patches/qt/fix_configure_mac.patch b/depends/patches/qt/fix_configure_mac.patch
--- a/depends/patches/qt/fix_configure_mac.patch
+++ b/depends/patches/qt/fix_configure_mac.patch
@@ -27,3 +27,24 @@
 +            error("Could not resolve SDK $$info for \'$$sdk\' using $$infoarg")
          cache(QMAKE_MAC_SDK.$${sdk}.$${info}, set stash, QMAKE_MAC_SDK.$${sdk}.$${info})
      }
+
+--- old/qtbase/configure	2018-02-08 10:24:48.000000000 -0800
++++ new/qtbase/configure	2018-03-23 05:42:29.000000000 -0700
+@@ -232,8 +232,13 @@
+ 
+     sdk=$(getSingleQMakeVariable "QMAKE_MAC_SDK" "$1")
+     if [ -z "$sdk" ]; then echo "QMAKE_MAC_SDK must be set when building on Mac" >&2; exit 1; fi
+-    sysroot=$(/usr/bin/xcrun --sdk $sdk --show-sdk-path 2>/dev/null)
+-    if [ -z "$sysroot" ]; then echo "Failed to resolve SDK path for '$sdk'" >&2; exit 1; fi
++    sysroot=$(getSingleQMakeVariable "QMAKE_MAC_SDK_PATH" "$1")
++
++    echo "sysroot pre-configured as $sysroot";
++    if [ -z "$sysroot" ]; then
++       sysroot=$(/usr/bin/xcrun --sdk $sdk --show-sdk-path 2>/dev/null)
++       if [ -z "$sysroot" ]; then echo "Failed to resolve SDK path for '$sdk'" >&2; exit 1; fi
++    fi
+ 
+     case "$sdk" in
+         macosx*)
+
+
